### ISSUE TITLE
Log file, where is it located?

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#139]
I did not found the application log file? Perharps only existing in debug mode ?

**Comment by algorys** [comment]
Yes, currently, for windows user, log file is not easy to find.

It is located in folder of library in fact : `C:\Users\user\AppData\Roaming\Python\alignak_app`

For Linux, it's already under application folder. See http://alignak-app.readthedocs.io/en/develop/config.html#on-windows for more details.

Otherwise, ASAP I will try to put log file in another folder for Windows users, see #121.

The log file exist even debug mode is not activate (but with less informations)

**Comment by algorys** [comment]
This is now indicated in `settings.cfg` file.
