### ISSUE TITLE
Synthesis view: services list

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#96]
On the synthesis view, the services list may be sorted. But what is the best sort criteria: service_description, alias, last check time ? To be discussed

As an example, the WebUI is using the service aggregation parameter and then sorts ascending by service name/alias:
![image](https://cloud.githubusercontent.com/assets/2932687/21173478/3117b9b2-c1d8-11e6-8e82-11d3987597ba.png)

**Comment by algorys** [comment]
Currently, it's very hard for me to do that kind of view. That's why Synthesis View:

1. propose now sorted services A to Z
2. propose `filters` to display only aggregation you want and in which case you want. e.g. Just `Health` and `UNKNOWN` services
3. Display aggregation name in service description.

**Comment by mohierf** [comment]
It is ok as of now 😉
